### ISSUE TITLE
Arduino integration

### ISSUE THREAD

**Issue by sdasilvaENSEIRB** [Remi-p/Android-ColorSpeed#1]
#ClémentBougeTesFesses

**Comment by Remi-p** [comment]
WIP ; Nécessite une conversion du signal 12V <> 5v (ou autre, étant donné que les protocoles ODB font [ce qu'ils veulent](http://www.elm327.fr/norme-obd/modes-obd/)).
Les normes ISO sont payantes, impossible à vérifier de façon théorique, mais : [univers-volvo](http://forum.univers-volvo.com/showthread.php?tid=18504&pid=294803)
>Attention:Bien que le protocole soit celui du RS232 les niveaux de tensions sont différents. Impossible donc réaliser une connexion directe sur le PC, le niveau haut est celui de la batterie, par conséquent les contrôleurs de tension de l'ordinateur risquent de ne pas apprécier.
